<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use App\Models\Festival;

class FestivalSeeder extends Seeder
{
    public function run(): void
    {
        $festivals = [
            [
                'mk'  => 'Традиционални песни и ора',
                'en'  => 'Traditional Songs and Dances',
                'sr'  => 'Традиционалне песме и игре',
                'hr'  => 'Tradicionalne pjesme i plesovi',
                'bg'  => 'Традиционни песни и танци',
                'pl'  => 'Tradycyjne pieśni i tańce',
                'uk'  => 'Традиційні пісні та танці',
                'ro'  => 'Cântece și dansuri tradiționale',
                'tr'  => 'Geleneksel Şarkılar ve Danslar',
                'start'    => '2025-04-10',
                'end'      => '2025-04-14',
                'location' => 'Ohrid',
            ],
            [
                'mk'  => 'Традиционални песни и ора',
                'en'  => 'Traditional Songs and Dances',
                'sr'  => 'Традиционалне песме и игре',
                'hr'  => 'Tradicionalne pjesme i plesovi',
                'bg'  => 'Традиционни песни и танци',
                'pl'  => 'Tradycyjne pieśni i tańce',
                'uk'  => 'Традиційні пісні та танці',
                'ro'  => 'Cântece și dansuri tradiționale',
                'tr'  => 'Geleneksel Şarkılar ve Danslar',
                'start'    => '2025-04-24',
                'end'      => '2025-04-28',
                'location' => 'Ohrid',
            ],
            [
                'mk'  => 'Св. Климент и Наум Охридски',
                'en'  => 'St. Clement and Naum of Ohrid',
                'sr'  => 'Свети Климент и Наум Охридски',
                'hr'  => 'Sv. Kliment i Naum Ohridski',
                'bg'  => 'Св. Климент и Наум Охридски',
                'pl'  => 'Św. Klemens i Naum z Ochrydu',
                'uk'  => 'Св. Климент і Наум Охридські',
                'ro'  => 'Sf. Clement și Naum din Ohrid',
                'tr'  => 'Aziz Kliment ve Naum Ohridli',
                'start'    => '2025-05-08',
                'end'      => '2025-05-12',
                'location' => 'Ohrid',
            ],
            [
                'mk'  => 'Св. Климент и Наум Охридски',
                'en'  => 'St. Clement and Naum of Ohrid',
                'sr'  => 'Свети Климент и Наум Охридски',
                'hr'  => 'Sv. Kliment i Naum Ohridski',
                'bg'  => 'Св. Климент и Наум Охридски',
                'pl'  => 'Św. Klemens i Naum z Ochrydu',
                'uk'  => 'Св. Климент і Наум Охридські',
                'ro'  => 'Sf. Clement și Naum din Ohrid',
                'tr'  => 'Aziz Kliment ve Naum Ohridli',
                'start'    => '2025-05-22',
                'end'      => '2025-05-26',
                'location' => 'Ohrid',
            ],
            [
                'mk'  => 'Езерска Разгледница',
                'en'  => 'Lake Postcard',
                'sr'  => 'Језерска разгледница',
                'hr'  => 'Razglednica s Jezera',
                'bg'  => 'Езерска Разгледница',
                'pl'  => 'Kartka z jeziora',
                'uk'  => 'Листівка з озера',
                'ro'  => 'Carte poștală de lac',
                'tr'  => 'Göl Kartpostalı',
                'start'    => '2025-06-04',
                'end'      => '2025-06-09',
                'location' => 'Ohrid',
            ],
            [
                'mk'  => 'Езерска Разгледница',
                'en'  => 'Lake Postcard',
                'sr'  => 'Језерска разгледница',
                'hr'  => 'Razglednica s Jezera',
                'bg'  => 'Езерска Разгледница',
                'pl'  => 'Kartka z jeziora',
                'uk'  => 'Листівка з озера',
                'ro'  => 'Carte poștală de lac',
                'tr'  => 'Göl Kartpostalı',
                'start'    => '2025-06-19',
                'end'      => '2025-06-23',
                'location' => 'Ohrid',
            ],
            [
                'mk'  => 'Езерска Разгледница',
                'en'  => 'Lake Postcard',
                'sr'  => 'Језерска разгледница',
                'hr'  => 'Razglednica s Jezera',
                'bg'  => 'Езерска Разгледница',
                'pl'  => 'Kartka z jeziora',
                'uk'  => 'Листівка з озера',
                'ro'  => 'Carte poștală de lac',
                'tr'  => 'Göl Kartpostalı',
                'start'    => '2025-06-26',
                'end'      => '2025-06-30',
                'location' => 'Ohrid',
            ],
            [
                'mk'  => 'Охридски фолклорни денови',
                'en'  => 'Ohrid Folklore Days',
                'sr'  => 'Охридски дани фолклора',
                'hr'  => 'Dani folklora Ohrid',
                'bg'  => 'Охридски фолклорни дни',
                'pl'  => 'Dni folkloru ochrydzkiego',
                'uk'  => 'Дні фольклору Охриду',
                'ro'  => 'Zilele folclorului Ohrid',
                'tr'  => 'Ohri Folklor Günleri',
                'start'    => '2025-07-03',
                'end'      => '2025-07-07',
                'location' => 'Ohrid',
            ],
            [
                'mk'  => 'Охридски фолклорни денови',
                'en'  => 'Ohrid Folklore Days',
                'sr'  => 'Охридски дани фолклора',
                'hr'  => 'Dani folklora Ohrid',
                'bg'  => 'Охридски фолклорни дни',
                'pl'  => 'Dni folkloru ochrydzkiego',
                'uk'  => 'Дні фольклору Охриду',
                'ro'  => 'Zilele folclorului Ohrid',
                'tr'  => 'Ohri Folklor Günleri',
                'start'    => '2025-07-10',
                'end'      => '2025-07-14',
                'location' => 'Ohrid',
            ],
            [
                'mk'  => 'Охридски фолклорни денови',
                'en'  => 'Ohrid Folklore Days',
                'sr'  => 'Охридски дани фолклора',
                'hr'  => 'Dani folklora Ohrid',
                'bg'  => 'Охридски фолклорни дни',
                'pl'  => 'Dni folkloru ochrydzkiego',
                'uk'  => 'Дні фольклору Охриду',
                'ro'  => 'Zilele folclorului Ohrid',
                'tr'  => 'Ohri Folklor Günleri',
                'start'    => '2025-07-17',
                'end'      => '2025-07-21',
                'location' => 'Ohrid',
            ],
            [
                'mk'  => 'Охридски фолклорни денови',
                'en'  => 'Ohrid Folklore Days',
                'sr'  => 'Охридски дани фолклора',
                'hr'  => 'Dani folklora Ohrid',
                'bg'  => 'Охридски фолклорни дни',
                'pl'  => 'Dni folkloru ochrydzkiego',
                'uk'  => 'Дні фольклору Охриду',
                'ro'  => 'Zilele folclorului Ohrid',
                'tr'  => 'Ohri Folklor Günleri',
                'start'    => '2025-07-24',
                'end'      => '2025-07-28',
                'location' => 'Ohrid',
            ],
            [
                'mk'  => 'Здравко Банар',
                'en'  => 'Zdravko Banar',
                'sr'  => 'Здравко Банар',
                'hr'  => 'Zdravko Banar',
                'bg'  => 'Здравко Банар',
                'pl'  => 'Zdravko Banar',
                'uk'  => 'Здравко Банар',
                'ro'  => 'Zdravko Banar',
                'tr'  => 'Zdravko Banar',
                'start'    => '2025-08-07',
                'end'      => '2025-08-11',
                'location' => 'Ohrid',
            ],
            [
                'mk'  => 'Здравко Банар',
                'en'  => 'Zdravko Banar',
                'sr'  => 'Здравко Банар',
                'hr'  => 'Zdravko Banar',
                'bg'  => 'Здравко Банар',
                'pl'  => 'Zdravko Banar',
                'uk'  => 'Здравко Банар',
                'ro'  => 'Zdravko Banar',
                'tr'  => 'Zdravko Banar',
                'start'    => '2025-08-14',
                'end'      => '2025-08-18',
                'location' => 'Ohrid',
            ],
            [
                'mk'  => 'Здравко Банар',
                'en'  => 'Zdravko Banar',
                'sr'  => 'Здравко Банар',
                'hr'  => 'Zdravко Banar',
                'bg'  => 'Здравко Банар',
                'pl'  => 'Zдравко Banар',
                'uk'  => 'Здравко Банар',
                'ro'  => 'Zдравко Банар',
                'tr'  => 'Zдравко Banар',
                'start'    => '2025-08-21',
                'end'      => '2025-08-25',
                'location' => 'Ohrid',
            ],
            [
                'mk'  => 'Здравко Банар',
                'en'  => 'Zdravko Banar',
                'sr'  => 'Здравко Банар',
                'hr'  => 'Zдравко Banар',
                'bg'  => 'Здравко Банар',
                'pl'  => 'Zдравко Banар',
                'uk'  => 'Здравко Банар',
                'ro'  => 'Zдравко Banар',
                'tr'  => 'Zdravко Банар',
                'start'    => '2025-08-28',
                'end'      => '2025-09-01',
                'location' => 'Ohrid',
            ],
            [
                'mk'  => 'Атанас Колароски',
                'en'  => 'Atanas Kolaroski',
                'sr'  => 'Атанас Колароски',
                'hr'  => 'Atanas Kolaroski',
                'bg'  => 'Атанас Колароски',
                'pl'  => 'Atanas Kolaroski',
                'uk'  => 'Атанас Колароський',
                'ro'  => 'Atanas Kolaroski',
                'tr'  => 'Atanas Kolaroski',
                'start'    => '2025-09-04',
                'end'      => '2025-09-08',
                'location' => 'Struga',
            ],
            [
                'mk'  => 'Атанас Колароски',
                'en'  => 'Atanas Kolaroski',
                'sr'  => 'Атанас Колароски',
                'hr'  => 'Atanas Kolaroski',
                'bg'  => 'Атанас Колароски',
                'pl'  => 'Atanas Kolaroski',
                'uk'  => 'Атанас Колароський',
                'ro'  => 'Atanas Kolaroski',
                'tr'  => 'Atanas Kolaroski',
                'start'    => '2025-09-11',
                'end'      => '2025-09-15',
                'location' => 'Struga',
            ],
            [
                'mk'  => 'Атанас Колароски',
                'en'  => 'Atanas Kolaroski',
                'sr'  => 'Атанас Колароски',
                'hr'  => 'Atanas Kolaroski',
                'bg'  => 'Атанас Колароски',
                'pl'  => 'Atanas Kolaroski',
                'uk'  => 'Атанас Колароський',
                'ro'  => 'Atanas Kolaroski',
                'tr'  => 'Atanas Kolaroski',
                'start'    => '2025-09-25',
                'end'      => '2025-09-29',
                'location' => 'Struga',
            ],
            [
                'mk'  => 'Фолклорна есен',
                'en'  => 'Folklore Fall',
                'sr'  => 'Јесен фолклора',
                'hr'  => 'Jesen folklora',
                'bg'  => 'Фолклорна есен',
                'pl'  => 'Jesień folkloru',
                'uk'  => 'Осінь фольклору',
                'ro'  => 'Toamnă folclorică',
                'tr'  => 'Folklor Güzü',
                'start'    => '2025-10-02',
                'end'      => '2025-10-06',
                'location' => 'Ohrid',
            ],
            [
                'mk'  => 'Фолклорна есен',
                'en'  => 'Folklore Fall',
                'sr'  => 'Јесен фолклора',
                'hr'  => 'Jesen folklora',
                'bg'  => 'Фолклорна есен',
                'pl'  => 'Jesień folkloru',
                'uk'  => 'Осінь фольклору',
                'ro'  => 'Toamnă folclorică',
                'tr'  => 'Folklor Güzü',
                'start'    => '2025-10-16',
                'end'      => '2025-10-20',
                'location' => 'Ohrid',
            ],
            [
                'mk'  => 'Ноември во Охрид',
                'en'  => 'November in Ohrid',
                'sr'  => 'Новембар у Охриду',
                'hr'  => 'Studeni u Ohridu',
                'bg'  => 'Ноември в Охрид',
                'pl'  => 'Listopad w Ohridzie',
                'uk'  => 'Листопад в Охриді',
                'ro'  => 'Noiembrie în Ohrid',
                'tr'  => 'Kasım Ohrid’de',
                'start'    => '2025-11-13',
                'end'      => '2025-11-17',
                'location' => 'Ohrid',
            ],
            [
                'mk'  => 'Ноември во Охрид',
                'en'  => 'November in Ohrid',
                'sr'  => 'Новембар у Охриду',
                'hr'  => 'Studeni u Ohridu',
                'bg'  => 'Ноември в Охрид',
                'pl'  => 'Listopad w Ohridzie',
                'uk'  => 'Листопад в Охриді',
                'ro'  => 'Noiembrie în Ohrid',
                'tr'  => 'Kasım Ohrid’de',
                'start'    => '2025-11-27',
                'end'      => '2025-12-01',
                'location' => 'Ohrid',
            ],
        ];

        foreach ($festivals as $f) {
            Festival::create([
                'name_mk'    => $f['mk'],
                'name_en'    => $f['en'],
                'name_sr'    => $f['sr'],
                'name_hr'    => $f['hr'],
                'name_bg'    => $f['bg'],
                'name_pl'    => $f['pl'],
                'name_uk'    => $f['uk'],
                'name_ro'    => $f['ro'],
                'name_tr'    => $f['tr'],
                'slug'       => Str::slug($f['en'] . '-' . $f['start']),
                'start_date' => $f['start'],
                'end_date'   => $f['end'],
                'location'   => $f['location'],
                'year'       => 2025,
            ]);
        }
    }
}
